ktor:
    application:
        modules:
            - hu.notkulonme.ApplicationKt.module
    deployment:
        port: 8080
api:
    database_url : "http://localhost:3000/customers"
    assets : "assets/"